export const Data = [
  {
    id: 1,
    title: "Margherita",
    description: "Tomato sauce,mozzarella",
    price: "10",
    category: "pizza",
    quantity: 1,
  },
  {
    id: 2,
    title: "Melanzane",
    description: "Tomato sauce, mozzarella, aubergines, black olives, garlic",
    price: "12",
    category: "pizza",
    quantity: 1,
  },
  {
    id: 3,
    title: "La PizzaVerde",
    description:
      "Tomato sauce, mozzarella, green peppers, jalapeños, green olives",
    price: "8",
    category: "pizza",
    quantity: 1,
  },
  {
    id: 4,
    title: "Prosciutto",
    description: "Tomato sauce, mozzarella, ham",
    price: "9",
    category: "pizza",
    quantity: 1,
  },
  {
    id: 5,
    title: "Salame",
    description: "Tomato sauce, mozzarella, salami",
    price: "7",
    category: "pizza",
    quantity: 1,
  },
  {
    id: 6,
    title: "Funghi",
    description: "Tomato sauce, mozzarella,mushrooms",
    price: "8",
    category: "pizza",
    quantity: 1,
  },
];
